### ISSUE TITLE
   using Castle.Facilities.TypedFactory;

### ISSUE THREAD

**Issue by xdvarpunen** [horsdal/Restbucks-on-Nancy#6]
Hi,

I just noticed you are using TypedFactory here https://github.com/horsdal/Restbucks-on-Nancy/blob/master/RestBucks/Bootstrapper.cs#L11 but removed the usage here:
https://github.com/horsdal/Restbucks-on-Nancy/commit/9d2c759a23383c2552e6c7e66a41683b9b471bd9#diff-e65433d83f6b096f195e7c63a0174747L56

And then found the TypedFactory here https://github.com/horsdal/Restbucks-on-Nancy/blob/5cf27eaa16beb46e3fd20045f92391cc3facca44/RestBucks/App_Start/WebApiInitializer.cs#L26.

Question is how you are utilizing the TypedFactory..? Just checking how you implemented SessionFactory (found your way of implementing the session-per-request for the NHibernate in Nancy). You made me start use and enjoy using the Castle Windsor :D Thanks for that!

Also why not use NHibernate Facility?

-XDVarpunen

**Comment by horsdal** [comment]
I am not maintaining this sample anymore and I have not touched it in a loooong time, so I honestly cannot remember, although some of that code might just have been over directly from the original sample at http://restbucks.codeplex.com/
